# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/raesangur/github/atelier-4/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0_1/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0837_axis_register_slice_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/raesangur/github/atelier-4/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0_1/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0837_axis_register_slice_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/raesangur/github/atelier-4/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0_1/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0837_axis_register_slice_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/raesangur/github/atelier-4/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0_1/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0837_axis_register_slice_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
